<#
.SYNOPSIS
    Nursify Global Testing Startup Script
.DESCRIPTION
    Starts ngrok, updates .env automatically, starts backend, and launches Expo in tunnel mode
#>

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "       NURSIFY - GLOBAL TESTING STARTUP                         " -ForegroundColor Cyan
Write-Host "       This script automates your ngrok + Expo setup            " -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$serverPath = Join-Path $scriptPath "Server"
$appPath = Join-Path $scriptPath "App"
$envFile = Join-Path $appPath ".env"

# Step 1: Check if ngrok is installed
Write-Host "[1/5] Checking ngrok installation..." -ForegroundColor Yellow
$ngrokPath = Get-Command ngrok -ErrorAction SilentlyContinue
if (-not $ngrokPath) {
    Write-Host "[ERROR] ngrok not found! Install it from https://ngrok.com/download" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] ngrok found at: $($ngrokPath.Source)" -ForegroundColor Green

# Step 2: Start ngrok in background
Write-Host ""
Write-Host "[2/5] Starting ngrok tunnel on port 5000..." -ForegroundColor Yellow

# Kill existing ngrok processes
Get-Process ngrok -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

# Start ngrok in a new window
Start-Process powershell -ArgumentList "-NoExit", "-Command", "ngrok http 5000" -WindowStyle Normal

# Wait for ngrok to start
Write-Host "   Waiting for ngrok to initialize..." -ForegroundColor Gray
Start-Sleep -Seconds 5

# Step 3: Get ngrok URL from API
Write-Host ""
Write-Host "[3/5] Getting ngrok public URL..." -ForegroundColor Yellow

$maxRetries = 10
$ngrokUrl = $null

for ($i = 1; $i -le $maxRetries; $i++) {
    try {
        $tunnels = Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels' -TimeoutSec 5
        $ngrokUrl = ($tunnels.tunnels | Where-Object { $_.proto -eq 'https' } | Select-Object -First 1).public_url
        if ($ngrokUrl) {
            break
        }
    } catch {
        Write-Host "   Retry $i/$maxRetries - ngrok not ready yet..." -ForegroundColor Gray
        Start-Sleep -Seconds 2
    }
}

if (-not $ngrokUrl) {
    Write-Host "[ERROR] Could not get ngrok URL. Check the ngrok window for errors." -ForegroundColor Red
    exit 1
}

Write-Host "[OK] ngrok URL: $ngrokUrl" -ForegroundColor Green

# Step 4: Update .env file
Write-Host ""
Write-Host "[4/5] Updating App/.env with ngrok URL..." -ForegroundColor Yellow

$envContent = @"
# ==================================================================
# NURSIFY APP ENVIRONMENT CONFIGURATION
# ==================================================================
# AUTO-GENERATED by start-global.ps1 at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# ==================================================================

# [OK] Current ngrok URL (auto-updated)
EXPO_PUBLIC_BASE_URL=$ngrokUrl
EXPO_PUBLIC_API_URL=$ngrokUrl/api
"@

Set-Content -Path $envFile -Value $envContent -Encoding UTF8
Write-Host "[OK] Updated $envFile" -ForegroundColor Green

# Step 5: Start Backend
Write-Host ""
Write-Host "[5/5] Starting backend server..." -ForegroundColor Yellow

Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$serverPath'; npm start" -WindowStyle Normal

Start-Sleep -Seconds 3

# Final instructions
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "                    [OK] SETUP COMPLETE!                        " -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "ngrok URL: $ngrokUrl" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next step - Start Expo in a NEW terminal:" -ForegroundColor Yellow
Write-Host ""
Write-Host "   cd App" -ForegroundColor White
Write-Host "   npx expo start --tunnel --clear" -ForegroundColor White
Write-Host ""
Write-Host "Then scan the QR code with Expo Go from ANY device/network!" -ForegroundColor Green
Write-Host ""

# Copy URL to clipboard
$ngrokUrl | Set-Clipboard
Write-Host "[CLIPBOARD] ngrok URL copied to clipboard!" -ForegroundColor Gray
Write-Host ""
Write-Host "Press any key to close this window..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
