#!/usr/bin/env node

/**
 * Automatic IP Detection & .env Update Script
 * 
 * Purpose:
 * - Detects the current local IPv4 address
 * - Updates .env file with EXPO_PUBLIC_API_URL
 * - Ensures Expo Go app always connects to the correct backend
 * 
 * This script runs automatically before 'expo start' via npm prestart hook
 * 
 * Cross-platform compatible: Windows, macOS, Linux
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

// Configuration
const BACKEND_PORT = '5000';
const ENV_FILE_PATH = path.join(__dirname, '..', '.env');
const API_CONFIG_PATH = path.join(__dirname, '..', 'config', 'api.js');

/**
 * Detect the active local IPv4 address
 * Filters out internal loopback addresses and prioritizes non-internal IPs
 */
function detectLocalIP() {
    const interfaces = os.networkInterfaces();
    
    // Priority order: Ethernet > WiFi > Others
    const priorityOrder = ['eth', 'en', 'wlan', 'wi-fi', 'ethernet'];
    
    let fallbackIP = null;
    let detectedIP = null;
    
    // First pass: look for priority interfaces
    for (const interfaceName of Object.keys(interfaces)) {
        const interfaceInfo = interfaces[interfaceName];
        
        for (const info of interfaceInfo) {
            // Skip non-IPv4 and internal addresses
            if (info.family !== 'IPv4' || info.internal) {
                continue;
            }
            
            // Store first valid IP as fallback
            if (!fallbackIP) {
                fallbackIP = info.address;
            }
            
            // Check if this is a priority interface
            const lowerName = interfaceName.toLowerCase();
            if (priorityOrder.some(prefix => lowerName.includes(prefix))) {
                detectedIP = info.address;
                console.log(`✅ Detected IP from ${interfaceName}: ${detectedIP}`);
                return detectedIP;
            }
        }
    }
    
    // Return fallback or localhost
    const finalIP = detectedIP || fallbackIP || '127.0.0.1';
    console.log(`✅ Using IP address: ${finalIP}`);
    return finalIP;
}

/**
 * Update the api.js file directly with the new IP
 * This is more reliable than .env for Expo
 */
function updateApiConfig(ipAddress) {
    const apiUrl = `http://${ipAddress}:${BACKEND_PORT}/api`;
    const baseUrl = `http://${ipAddress}:${BACKEND_PORT}`;
    
    // Read the existing api.js file
    if (!fs.existsSync(API_CONFIG_PATH)) {
        console.error(`❌ Error: api.js not found at ${API_CONFIG_PATH}`);
        process.exit(1);
    }
    
    const apiContent = fs.readFileSync(API_CONFIG_PATH, 'utf8');
    
    // Replace the IP address in the file
    // Match: const SERVER_IP = 'xxx.xxx.xxx.xxx';
    const updatedContent = apiContent.replace(
        /const SERVER_IP = ['"][\d.]+['"];/,
        `const SERVER_IP = '${ipAddress}';`
    );
    
    // Write back to file
    fs.writeFileSync(API_CONFIG_PATH, updatedContent, 'utf8');
    console.log(`✅ Updated api.js: ${API_CONFIG_PATH}`);
    console.log(`📱 API URL: ${apiUrl}`);
}

/**
 * Update or create .env file with the new IP (backup method)
 */
function updateEnvFile(ipAddress) {
    const apiUrl = `http://${ipAddress}:${BACKEND_PORT}/api`;
    const baseUrl = `http://${ipAddress}:${BACKEND_PORT}`;
    
    let envContent = '';
    let existingContent = {};
    
    // Read existing .env if it exists
    if (fs.existsSync(ENV_FILE_PATH)) {
        const currentContent = fs.readFileSync(ENV_FILE_PATH, 'utf8');
        
        // Parse existing environment variables
        currentContent.split('\n').forEach(line => {
            const trimmedLine = line.trim();
            if (trimmedLine && !trimmedLine.startsWith('#')) {
                const [key, ...valueParts] = trimmedLine.split('=');
                if (key) {
                    existingContent[key.trim()] = valueParts.join('=').trim();
                }
            }
        });
    }
    
    // Update or add the new values
    existingContent['EXPO_PUBLIC_API_URL'] = apiUrl;
    existingContent['EXPO_PUBLIC_BASE_URL'] = baseUrl;
    existingContent['EXPO_PUBLIC_SERVER_IP'] = ipAddress;
    existingContent['EXPO_PUBLIC_SERVER_PORT'] = BACKEND_PORT;
    
    // Build the new .env content
    envContent += '# Auto-generated by update-ip.js script\n';
    envContent += `# Last updated: ${new Date().toISOString()}\n`;
    envContent += '# Do not manually edit these values - they are auto-detected\n\n';
    
    envContent += '# Backend API Configuration (Auto-detected)\n';
    envContent += `EXPO_PUBLIC_API_URL=${existingContent['EXPO_PUBLIC_API_URL']}\n`;
    envContent += `EXPO_PUBLIC_BASE_URL=${existingContent['EXPO_PUBLIC_BASE_URL']}\n`;
    envContent += `EXPO_PUBLIC_SERVER_IP=${existingContent['EXPO_PUBLIC_SERVER_IP']}\n`;
    envContent += `EXPO_PUBLIC_SERVER_PORT=${existingContent['EXPO_PUBLIC_SERVER_PORT']}\n`;
    
    // Add any other existing env vars (that aren't our auto-generated ones)
    const autoGenKeys = ['EXPO_PUBLIC_API_URL', 'EXPO_PUBLIC_BASE_URL', 'EXPO_PUBLIC_SERVER_IP', 'EXPO_PUBLIC_SERVER_PORT'];
    const otherKeys = Object.keys(existingContent).filter(key => !autoGenKeys.includes(key));
    
    if (otherKeys.length > 0) {
        envContent += '\n# Other Configuration\n';
        otherKeys.forEach(key => {
            envContent += `${key}=${existingContent[key]}\n`;
        });
    }
    
    // Write to file
    fs.writeFileSync(ENV_FILE_PATH, envContent, 'utf8');
    console.log(`✅ Updated .env file: ${ENV_FILE_PATH}`);
    console.log(`📱 API URL: ${apiUrl}`);
}

/**
 * Main execution
 */
function main() {
    console.log('\n🔍 Auto-detecting local IP address...\n');
    
    try {
        const ipAddress = detectLocalIP();
        
        // Update api.js directly (primary method for Expo)
        updateApiConfig(ipAddress);
        
        // Also update .env as backup
        updateEnvFile(ipAddress);
        
        console.log('\n✨ IP detection complete!');
        console.log('🚀 Your Expo app will now connect to the correct backend.\n');
        
        process.exit(0);
    } catch (error) {
        console.error('❌ Error during IP detection:', error.message);
        console.error('\n💡 Tip: Make sure you are connected to a network.');
        process.exit(1);
    }
}

// Run if executed directly
if (require.main === module) {
    main();
}

module.exports = { detectLocalIP, updateEnvFile };
